

const startingBoard = {
    tiles: {
        a1: { occupied: true, occupier: "rook", isWhite: true },
        a2: { occupied: true, occupier: "pawn", isWhite: true },
        a3: { occupied: false, occupier: null },
        a4: { occupied: false, occupier: null },
        a5: { occupied: false, occupier: null },
        a6: { occupied: false, occupier: null },
        a7: { occupied: true, occupier: "pawn", isWhite: false },
        a8: { occupied: true, occupier: "rook", isWhite: false },
        b1: { occupied: true, occupier: "knight", isWhite: true },
        b2: { occupied: true, occupier: "pawn", isWhite: true },
        b3: { occupied: false, occupier: null },
        b4: { occupied: false, occupier: null },
        b5: { occupied: false, occupier: null },
        b6: { occupied: false, occupier: null },
        b7: { occupied: true, occupier: "pawn", isWhite: false },
        b8: { occupied: true, occupier: "knight", isWhite: false },
        c1: { occupied: true, occupier: "bishop", isWhite: true },
        c2: { occupied: true, occupier: "pawn", isWhite: true },
        c3: { occupied: false, occupier: null },
        c4: { occupied: false, occupier: null },
        c5: { occupied: false, occupier: null },
        c6: { occupied: false, occupier: null },
        c7: { occupied: true, occupier: "pawn", isWhite: false },
        c8: { occupied: true, occupier: "bishop", isWhite: false },
        d1: { occupied: true, occupier: "queen", isWhite: true },
        d2: { occupied: true, occupier: "pawn", isWhite: true },
        d3: { occupied: false, occupier: null },
        d4: { occupied: false, occupier: null },
        d5: { occupied: false, occupier: null },
        d6: { occupied: false, occupier: null },
        d7: { occupied: true, occupier: "pawn", isWhite: false },
        d8: { occupied: true, occupier: "queen", isWhite: false },
        e1: { occupied: true, occupier: "king", isWhite: true },
        e2: { occupied: true, occupier: "pawn", isWhite: true },
        e3: { occupied: false, occupier: null },
        e4: { occupied: false, occupier: null },
        e5: { occupied: false, occupier: null },
        e6: { occupied: false, occupier: null },
        e7: { occupied: true, occupier: "pawn", isWhite: false },
        e8: { occupied: true, occupier: "king", isWhite: false },
        f1: { occupied: true, occupier: "bishop", isWhite: true },
        f2: { occupied: true, occupier: "pawn", isWhite: true },
        f3: { occupied: false, occupier: null },
        f4: { occupied: false, occupier: null },
        f5: { occupied: false, occupier: null },
        f6: { occupied: false, occupier: null },
        f7: { occupied: true, occupier: "pawn", isWhite: false },
        f8: { occupied: true, occupier: "bishop", isWhite: false },
        g1: { occupied: true, occupier: "knight", isWhite: true },
        g2: { occupied: true, occupier: "pawn", isWhite: true },
        g3: { occupied: false, occupier: null },
        g4: { occupied: false, occupier: null },
        g5: { occupied: false, occupier: null },
        g6: { occupied: false, occupier: null },
        g7: { occupied: true, occupier: "pawn", isWhite: false },
        g8: { occupied: true, occupier: "knight", isWhite: false },
        h1: { occupied: true, occupier: "rook", isWhite: true },
        h2: { occupied: true, occupier: "pawn", isWhite: true },
        h3: { occupied: false, occupier: null },
        h4: { occupied: false, occupier: null },
        h5: { occupied: false, occupier: null },
        h6: { occupied: false, occupier: null },
        h7: { occupied: true, occupier: "pawn", isWhite: false },
        h8: { occupied: true, occupier: "rook", isWhite: false },
    },
};

export default startingBoard;